# Generated by Django 5.2.4 on 2025-07-08 20:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("about", models.TextField()),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("color", models.TextField(blank=True, null=True)),
                ("image", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "category",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorFilterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "verbose_name_plural": "indicator filters",
                "db_table": "indicator_filter_type",
            },
        ),
        migrations.CreateModel(
            name="IndicatorSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "indicator_source",
            },
        ),
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "location_type",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("color", models.TextField(blank=True, null=True)),
                ("image", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "section",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("universe_description", models.TextField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.category",
                    ),
                ),
            ],
            options={
                "db_table": "indicator",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorFilterOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "indicator_filter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicatorfiltertype",
                    ),
                ),
            ],
            options={
                "db_table": "indicator_filter_option",
                "ordering": ["sort_order"],
                "unique_together": {("name", "indicator_filter_type")},
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("color", models.TextField(blank=True, null=True)),
                (
                    "location_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.locationtype",
                    ),
                ),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_d3_indicator_viz.section",
            ),
        ),
        migrations.CreateModel(
            name="IndicatorDataVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "data_visual_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("ban", "Ban"),
                            ("column", "Column"),
                            ("donut", "Donut"),
                            ("min_med_max", "Min Med Max"),
                            ("line", "Line"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "location_comparison_type",
                    models.TextField(
                        blank=True,
                        choices=[("parents", "Parents"), ("siblings", "Siblings")],
                        null=True,
                    ),
                ),
                (
                    "value_field",
                    models.TextField(
                        choices=[
                            ("count", "Count"),
                            ("universe", "Universe"),
                            ("percentage", "Percentage"),
                            ("rate", "Rate"),
                            ("rate_per", "Rate Per"),
                            ("dollars", "Dollars"),
                            ("index", "Index"),
                        ]
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicator",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicatorsource",
                    ),
                ),
            ],
            options={
                "db_table": "indicator_data_visual",
                "ordering": [
                    "indicator__category__section__sort_order",
                    "indicator__category__sort_order",
                    "indicator__sort_order",
                ],
                "unique_together": {
                    ("indicator", "start_date", "end_date", "data_visual_type")
                },
            },
        ),
        migrations.CreateModel(
            name="IndicatorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("count", models.FloatField(blank=True, null=True)),
                ("count_moe", models.FloatField(blank=True, null=True)),
                ("universe", models.FloatField(blank=True, null=True)),
                ("universe_moe", models.FloatField(blank=True, null=True)),
                ("percentage", models.FloatField(blank=True, null=True)),
                ("percentage_moe", models.FloatField(blank=True, null=True)),
                ("rate", models.FloatField(blank=True, null=True)),
                ("rate_moe", models.FloatField(blank=True, null=True)),
                ("rate_per", models.FloatField(blank=True, null=True)),
                ("dollars", models.FloatField(blank=True, null=True)),
                ("dollars_moe", models.FloatField(blank=True, null=True)),
                ("index", models.FloatField(blank=True, null=True)),
                ("index_moe", models.FloatField(blank=True, null=True)),
                (
                    "filter_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicatorfilteroption",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicator",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicatorsource",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.location",
                    ),
                ),
            ],
            options={
                "db_table": "indicator_value",
                "unique_together": {
                    (
                        "source",
                        "start_date",
                        "end_date",
                        "indicator",
                        "filter_option",
                        "location",
                    )
                },
            },
        ),
    ]
