# Generated by Django 5.2.6 on 2025-10-02 12:42

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_d3_indicator_viz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("colors", models.JSONField()),
            ],
            options={
                "db_table": "color_scale",
            },
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="universe_description",
            new_name="formatter",
        ),
        migrations.RenameField(
            model_name="indicatorvalue",
            old_name="dollars",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="indicatorvalue",
            old_name="dollars_moe",
            new_name="value_moe",
        ),
        migrations.RemoveField(
            model_name="indicatordatavisual",
            name="value_field",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="index",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="index_moe",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="percentage_moe",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="rate_moe",
        ),
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="rate_per",
        ),
        migrations.AddField(
            model_name="category",
            name="anchor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="indicator_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("percentage", "Percentage"),
                    ("average", "Average"),
                    ("median", "Median"),
                    ("count", "Count"),
                    ("rate", "Rate"),
                    ("index", "Index"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="qualifier",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="rate_per",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatavisual",
            name="columns",
            field=models.IntegerField(
                db_index=True,
                default=12,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="locationtype",
            name="parent_location_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_location_types",
                to="django_d3_indicator_viz.locationtype",
            ),
        ),
        migrations.AddField(
            model_name="locationtype",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="section",
            name="anchor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="indicatordatavisual",
            name="color_scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_d3_indicator_viz.colorscale",
            ),
        ),
        migrations.CreateModel(
            name="CustomLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("color", models.TextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=1000, unique=True)),
                ("organization", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.locationtype",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="custom_locations",
                        to="django_d3_indicator_viz.location",
                    ),
                ),
            ],
            options={
                "db_table": "custom_location",
            },
        ),
    ]
