# Generated by Django 5.2.8 on 2025-12-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_d3_indicator_viz", "0002_colorscale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="share_axes",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, all line and column charts in this category will share the same Y-axis scale for easier comparison.",
            ),
        ),
        migrations.AddField(
            model_name="indicatorvalue",
            name="active_data",
            field=models.BooleanField(default=False),
        ),
    ]
