# Generated by Django 5.2.8 on 2025-12-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_d3_indicator_viz",
            "0003_category_share_axes_indicatorvalue_active_data",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatordatavisual",
            name="source",
        ),
        migrations.CreateModel(
            name="IndicatorDataVisualSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Source priority: 0 = primary source, 1+ = fallback sources in order",
                    ),
                ),
                (
                    "data_visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicatordatavisual",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_d3_indicator_viz.indicatorsource",
                    ),
                ),
            ],
            options={
                "db_table": "indicator_data_visual_source",
                "ordering": ["priority"],
                "unique_together": {("data_visual", "source")},
            },
        ),
        migrations.AddField(
            model_name="indicatordatavisual",
            name="sources",
            field=models.ManyToManyField(
                help_text="Ordered list of data sources. First source is primary, rest are fallbacks.",
                related_name="data_visuals",
                through="django_d3_indicator_viz.IndicatorDataVisualSource",
                to="django_d3_indicator_viz.indicatorsource",
            ),
        ),
    ]
