# Generated by Django 6.0.4 on 2026-04-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_d3_indicator_viz', '0005_remove_category_share_axes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatavisual',
            name='data_visual_type',
            field=models.TextField(blank=True, choices=[('ban', 'Ban'), ('column', 'Column'), ('donut', 'Donut'), ('min_med_max', 'Min Med Max'), ('line', 'Line'), ('multiline', 'Multiline')], null=True),
        ),
        # Ensure the location table has a PRIMARY KEY constraint on id.
        # When earlier migrations were faked (e.g. on a database restored
        # from a dump), the PK constraint may be missing, which prevents
        # creating foreign keys that reference location.id.
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conrelid = 'location'::regclass
                          AND contype = 'p'
                    ) THEN
                        ALTER TABLE location ADD PRIMARY KEY (id);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='CopyDataEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_d3_indicator_viz.indicator')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_d3_indicator_viz.location')),
            ],
            options={
                'db_table': 'copy_data_event',
            },
        ),
    ]
