# Generated by Django 6.0.4 on 2026-04-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_d3_indicator_viz', '0005_remove_category_share_axes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatavisual',
            name='data_visual_type',
            field=models.TextField(blank=True, choices=[('ban', 'Ban'), ('column', 'Column'), ('donut', 'Donut'), ('min_med_max', 'Min Med Max'), ('line', 'Line'), ('multiline', 'Multiline')], null=True),
        ),
        migrations.CreateModel(
            name='CopyDataEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_d3_indicator_viz.indicator')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_d3_indicator_viz.location')),
            ],
            options={
                'db_table': 'copy_data_event',
            },
        ),
    ]
